services:
  prometheus:
    build: ./prometheus
    ports:
      - "9090:9090"
    networks:
      - app-network

  grafana:
    build: ./grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - app-network

volumes:
  grafana-storage:

networks:
  app-network:
    driver: bridge