#fichier docker-compose
services :
  webserver:
    build : ./
    container_name: webserver
    ports:
      - "80:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge