services:
  nginx:
    image: nginx:latest
    container_name: gateway
    volumes:
      - ./api-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - orders
      - auth
      - logs
      - users

  auth:
    build: auth-service
    container_name: auth-service
    networks:
      - app-network

  orders:
    build: orders-service
    container_name: orders-service
    networks:
      - app-network

  logs:
    build: logs-service
    container_name: logs-service
    networks:
      - app-network

  users:
    build: users-service
    container_name: users-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge