global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus-win'
    static_configs:
      - targets: ['host.docker.internal:8080']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']