#fichier docker-compose
services :
  webserver:
    build : web
    container_name: webserver
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge