name: Deploy to Server

on:
  push:
    branches:
      - main
      - test_cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Connexion SSH et déploiement des conteneurs
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/opt/Foodly/
            git pull origin main
            docker-compose up -f services/compose.yml --build -d