name: Deploy Frontend

on:
  push:
    branches:
      - main
    paths:
      - "apps/web/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du repo
        uses: actions/checkout@v4

      - name: Afficher l'IP publique du runner
        run: |
          echo "IP publique du runner GitHub :"
          curl https://api.ipify.org

      - name: Configuration SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H bubux.tlk.biz >> ~/.ssh/known_hosts

      - name: Déploiement sur le serveur distant
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no github-actions@bubux.tlk.biz << 'EOF'
            cd /opt/Foodly/apps/web
            git pull origin main
            docker compose up -d --build
          EOF
